[package]
name = "solana-svm-rent-collector"
description = "Solana SVM Rent Collector"
documentation = "https://docs.rs/solana-svm-rent-collector"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
solana-account = { workspace = true }
solana-clock = { workspace = true }
solana-pubkey = { workspace = true }
solana-rent = { workspace = true }
solana-rent-collector = { workspace = true }
solana-sdk-ids = { workspace = true }
solana-transaction-context = { workspace = true }
solana-transaction-error = { workspace = true }

[dev-dependencies]
solana-epoch-schedule = { workspace = true }
